services:
  database:
    image: mariadb:11.4
    container_name: yeohaeng-ttukttak-v3-database
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_DATABASE: yeohaeng_ttukttak_v3
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=FALSE
      - --bind-address=0.0.0.0
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    image: ${DOCKER_USERNAME}/yeohaeng-ttukttak-v3-server:latest
    container_name: yeohaeng-ttukttak-v3-server
    environment:
      JAVA_OPTS: -Dspring.profiles.active=dev -Djasypt.encryptor.password=${JASYPT_PASSWORD}

    ports:
      - "8080:8080"
    restart: always
    depends_on:
     database:
       condition: service_healthy
