spring:
  profiles:
    active: local

bayesian:
  entire-average: 3.475
  coefficient: 15.0
kakao:
  map:
    api-key: ENC(PbSFbZfTjOPh7SLcbhQhm58LUyk8NYksL8ES8sJ3FleJDd5lvMkXYk3gDAK/kkkD)

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:yeohaeng_ttukttak_v3;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        highlight_sql: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.yeohaeng_ttukttak.server: debug

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(KyvOUNBS0wVq3DbPqnHeoVLbYrAfifkk083N5tlIdqO4nB5R+bwdLfTa5CsSZ3f5+hi2FGRBavze+/tbxoixPg==)
    username: ENC(ukmkBnwGGffxfbsJxsOkqQ==)
    password: ENC(ZPsOy+pXF7H1LNmO4WtntUQQF4Uyel0y)

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations:
      - classpath:db/migration
      - classpath:db/data

---
spring:
  config:
    activate:
      on-profile: prod

  flyway:
    locations:
        - classpath:db/migration

bayesian:
  entire-average: 4.21756905
  coefficient: 5.0