spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:yeohaeng_ttukttak_v3
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  flyway:
    enabled: false

bayesian:
  entire-average: 3.475
  coefficient: 15.0

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

bayesian:
  entire-average: 4.21756905
  coefficient: 5.0