name: Deploy to Remote Server

on:
  push:
    branches:
      - main

env:
  CONTAINER_NAME: yeohaeng-ttukttak-v3-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: corretto

      - name: Execute Gradle build and push
        run: |
          ./gradlew bootBuildImage \
            -Pdocker_id=${{ secrets.DOCKER_USERNAME }} \
            -Pdocker_pw=${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy on remote server
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}:latest
          DOCKER_COMPOSE_FILE_URL: https://raw.githubusercontent.com/takeny1998/yeohaeng-ttukttak-v3-server/refs/heads/main/docker-compose.yml
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export JASYPT_PASSWORD=${{ secrets.JASYPT_PASSWORD }}
            
            docker compose down
            
            curl -k ${{ env.DOCKER_COMPOSE_FILE_URL }} > docker-compose.yaml
            docker compose pull
            docker compose up -d