name: Integration Test

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Set up JDK 23
          uses: actions/setup-java@v4
          with:
            java-version: 23
            distribution: corretto
  
        - name: Run Test with gradlew
          run: ./gradlew --info test
        
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
            junit_files: '**/build/test-results/test/TEST-*.xml'
